version: '3.3'

services:
  nginx:
    container_name: slacker_build_nginx

  api:
    container_name: slacker_build_api
    build:
      context: ./api-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets
    environment:
      DB_NAME: slacker_build

  auth:
    container_name: slacker_build_auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

  ui:
    container_name: slacker_build_ui
    build:
      context: ./ui-service
      dockerfile: Dockerfile.build

  db:
    container_name: slacker_build_db
    env_file:
      - .env
      - .build_env
      - .build_secrets
    environment:
      DB_NAME: slacker_build

  schema:
    container_name: slacker_build_schema
    build:
      context: ./schema
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets
      - .schema_build_secrets
    environment:
      DB_NAME: slacker_build

secrets:
  build_secrets:
    file: ./build_secrets.txt
  schema_build_secrets:
    file: ./schema_build_secrets.txt
