services:
  nginx:
    container_name: slacker_production_nginx
    env_file:
      - .env
      - .production_env
      - .production_secrets
    restart: always

  api:
    container_name: slacker_production_api
    image: docker.ikari.fi/slacker_build_api:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets
    restart: always

  auth:
    container_name: slacker_production_auth
    image: docker.ikari.fi/slacker_build_auth:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets
    restart: always

  ui:
    container_name: slacker_production_ui
    image: docker.ikari.fi/slacker_build_ui:${BUILD_TAG}
    restart: always

  db:
    container_name: slacker_production_db
    env_file:
      - .env
      - .production_env
      - .production_secrets
    environment:
      PGDATABASE: slacker_production
    restart: always

  zookeeper:
    container_name: slacker_production_zookeeper
    restart: always

  kafka:
    container_name: slacker_production_kafka
    restart: always

  ksqldb-server:
    container_name: slacker_production_ksqldb-server

  ksqldb-cli:
    container_name: slacker_production_ksqldb-cli

  schema:
    container_name: slacker_production_schema
    image: docker.ikari.fi/slacker_build_schema:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets

  adminer:
    container_name: slacker_production_adminer

secrets:
  production_secrets:
    file: ./production_secrets.txt
