version: '3.3'

services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3100"
    volumes:
    - ./api-service:/app

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3200"
    volumes:
    - ./auth-service:/app

  ui:
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    ports:
      - "80"
    volumes:
    - ./ui-service:/app

  db:
    ports:
      - "5432"

  zookeeper:
    ports:
      - "2181"

  kafka:
    ports:
      - "9092"

  ksqldb-server:
    ports:
      - "8088"

  ksqldb-cli:
    tty: true
    stdin_open: true

  schema:
    build: ./schema
    tty: true
    stdin_open: true

  adminer:
    ports:
      - "8080"
