version: '3.3'

services:
  nginx:
    image: nginx:1.19.9
    container_name: nginx
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - api
      - auth
      - ui
      - adminer
      - whoami
    command: [nginx-debug, '-g', 'daemon off;']

  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3100"
      - "9201:9201"
    environment:
      - SERVER_PORT=3100
      - DATABASE_CONNECTION_STRING=postgres://db:5432
    working_dir: /app
    volumes:
    - ./api-service:/app
    - api_node_modules:/app/node_modules
    networks:
      - default
    depends_on:
      - db
      - kafka
    command: sh -c "yarn run dev"

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3200"
      - "9202:9202"
    environment:
      - SERVER_PORT=3200
      - DATABASE_CONNECTION_STRING=postgres://db:5432
      - AUTH_API=https://accounts.google.com/o/oauth2/v2/auth
      - AUTH_CLIENT_ID=1091827026589-4c1icp593q61rr6a0ug316kue1fvmogv.apps.googleusercontent.com
      - AUTH_REDIRECT_URI=http://localhost:8080/auth/callback
    working_dir: /app
    volumes:
    - ./auth-service:/app
    - auth_node_modules:/app/node_modules
    networks:
      - default
    depends_on:
      - db
    command: sh -c "yarn run dev"

  ui:
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "3000"
      - "9203:9203"
    environment:
      - SERVER_PORT=3000
      - VIRTUAL_HOST=ui.local
      - VIRTUAL_PORT=3000
    working_dir: /app
    volumes:
    - ./ui-service:/app
    - ui_node_modules:/app/node_modules
    networks:
      - default
    depends_on:
      - api
    command: sh -c "yarn run start"

  schema:
    build: ./schema
    container_name: schema
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slacker
    working_dir: /app
    volumes:
    - ./schema:/app
    depends_on:
      - db
    command: sh -c "sleep infinity"

  db:
    image: postgres:13.2
    restart: always
    environment:
      PGDATA: /data/db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slacker
    container_name: db
    volumes:
    - postgres_data:/data
    networks:
      - default
    ports:
      - "5432"

  zookeeper:
    image: "docker.io/bitnami/zookeeper:3"
    container_name: zookeeper
    ports:
      - "2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - default
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "docker.io/bitnami/kafka:latest"
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - default
    ports:
      - "9092"
    depends_on:
      - zookeeper

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - default
    ports:
      - "8080"

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=8000
volumes:
  postgres_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  api_node_modules:
  auth_node_modules:
  ui_node_modules:
