services:
  api:
    image: docker.ikari.fi/slacker_build_api:${BUILD_TAG}

  auth:
    image: docker.ikari.fi/slacker_build_auth:${BUILD_TAG}

  ui:
    image: docker.ikari.fi/slacker_build_ui:${BUILD_TAG}

  schema:
    image: docker.ikari.fi/slacker_build_schema:${BUILD_TAG}
