version: '3.3'

services:
  nginx:
    env_file:
      - .env
      - .build_env
      - .build_secrets

  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

  ui:
    build:
      context: ./ui-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

  db:
    env_file:
      - .env
      - .build_env
      - .build_secrets
    environment:
      PGDATABASE: slacker_build

  zookeeper:
    env_file:
      - .env
      - .build_env
      - .build_secrets

  kafka:
    env_file:
      - .env
      - .build_env
      - .build_secrets

  ksqldb-server:
    env_file:
      - .env
      - .build_env
      - .build_secrets

  ksqldb-cli:
    env_file:
      - .env
      - .build_env
      - .build_secrets

  schema:
    build:
      context: ./schema
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

secrets:
  build_secrets:
    file: ./build_secrets.txt
