version: '3.3'

services:
  nginx:
    container_name: slacker_build_nginx
    env_file:
      - .env
      - .build_env
      - .build_secrets

  api:
    container_name: slacker_build_api
    build:
      context: ./api-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

  auth:
    container_name: slacker_build_auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

  ui:
    container_name: slacker_build_ui
    build:
      context: ./ui-service
      dockerfile: Dockerfile.build

  db:
    container_name: slacker_build_db
    env_file:
      - .env
      - .build_env
      - .build_secrets
    environment:
      PGDATABASE: slacker_build

  zookeeper:
    container_name: slacker_build_zookeeper

  kafka:
    container_name: slacker_build_kafka

  ksqldb-server:
    container_name: slacker_build_ksqldb-server

  ksqldb-cli:
    container_name: slacker_build_ksqldb-cli

  schema:
    container_name: slacker_build_schema
    build:
      context: ./schema
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

secrets:
  build_secrets:
    file: ./build_secrets.txt
