version: '3.3'

services:
  nginx:
    env_file:
      - .env
      - .development_env
      - .development_secrets

  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    env_file:
      - .env
      - .development_env
      - .development_secrets
    ports:
      - "9201"
    volumes:
    - ./api-service:/app
    - api_node_modules:/node_modules

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - .env
      - .development_env
      - .development_secrets
    ports:
      - "9202"
    volumes:
    - ./auth-service:/app
    - auth_node_modules:/node_modules

  ui:
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    env_file:
      - .env
      - .development_env
      - .development_secrets
    ports:
      - "9203"
    volumes:
    - ./ui-service:/app
    - ui_node_modules:/node_modules

  db:
    env_file:
      - .env
      - .development_env
      - .development_secrets
    environment:
      PGDATABASE: slacker_development

  zookeeper:
    env_file:
      - .env
      - .development_env
      - .development_secrets

  kafka:
    env_file:
      - .env
      - .development_env
      - .development_secrets

  ksqldb-server:
    env_file:
      - .env
      - .development_env
      - .development_secrets

  ksqldb-cli:
    env_file:
      - .env
      - .development_env
      - .development_secrets

  schema:
    build:
      context: ./schema
      dockerfile: Dockerfile
    env_file:
      - .env
      - .development_env
      - .development_secrets
    volumes:
    - ./schema:/app
    - schema_assets:/assets
    - schema_bundle:/bundle
    - schema_node_modules:/node_modules

  adminer:
    env_file:
      - .env
      - .development_env
      - .development_secrets

secrets:
  development_secrets:
    file: ./development_secrets.txt

volumes:
  auth_node_modules:
  api_node_modules:
  ui_node_modules:
  schema_assets:
  schema_bundle:
  schema_node_modules:
