version: '3.3'

services:
  nginx:
    container_name: slacker_build_nginx
    env_file:
      - .env
      - .build_env
      - .build_secrets

  api:
    container_name: slacker_build_api
    build:
      context: ./api-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets
    environment:
      DB_NAME: slacker_build

  auth:
    container_name: slacker_build_auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets

  ui:
    container_name: slacker_build_ui
    build:
      context: ./ui-service
      dockerfile: Dockerfile.build

  db:
    container_name: slacker_build_db
    env_file:
      - .env
      - .build_env
      - .build_secrets
      - .build_db_secrets
    environment:
      PGDATABASE: slacker_build
    volumes:
    - build_postgres_data:/data

  zookeeper:
    container_name: slacker_build_zookeeper
    volumes:
    - build_zookeeper_data:/data

  kafka:
    container_name: slacker_build_kafka
    volumes:
    - build_kafka_data:/data

  schema:
    container_name: slacker_build_schema
    build:
      context: ./schema
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
      - .build_secrets
      - .build_schema_secrets
    environment:
      DB_NAME: slacker_build

secrets:
  build_secrets:
    file: ./build_secrets.txt
  schema_build_secrets:
    file: ./build_schema_secrets.txt

volumes:
  build_postgres_data:
  build_zookeeper_data:
  build_kafka_data:
