services:
  nginx:
    env_file:
      - .env
      - .production_env
      - .production_secrets
    restart: always

  api:
    image: docker.ikari.fi/slacker_build_api:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets
    restart: always

  auth:
    image: docker.ikari.fi/slacker_build_auth:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets
    restart: always

  ui:
    image: docker.ikari.fi/slacker_build_ui:${BUILD_TAG}
    restart: always

  db:
    env_file:
      - .env
      - .production_env
      - .production_secrets
    environment:
      PGDATABASE: slacker_production
    restart: always

  zookeeper:
    restart: always
    env_file:
      - .env
      - .production_env
      - .production_secrets

  kafka:
    restart: always
    env_file:
      - .env
      - .production_env
      - .production_secrets

  ksqldb-server:
    env_file:
      - .env
      - .production_env
      - .production_secrets

  ksqldb-cli:
    env_file:
      - .env
      - .production_env
      - .production_secrets

  schema:
    image: docker.ikari.fi/slacker_build_schema:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets

  adminer:
    env_file:
      - .env
      - .production_env
      - .production_secrets

secrets:
  production_secrets:
    file: ./production_secrets.txt
