version: '3.3'

services:
  nginx:
    container_name: slacker_development_nginx
    env_file:
      - .env
      - .development_env
      - .development_secrets

  api:
    container_name: slacker_development_api
    build:
      context: ./api-service
      dockerfile: Dockerfile
    env_file:
      - .env
      - .development_env
      - .development_secrets
    volumes:
    - ./api-service:/app
    - api_node_modules:/node_modules

  auth:
    container_name: slacker_development_auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - .env
      - .development_env
      - .development_secrets
    volumes:
    - ./auth-service:/app
    - auth_node_modules:/node_modules

  ui:
    container_name: slacker_development_ui
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    volumes:
    - ./ui-service:/app
    - ui_node_modules:/node_modules

  db:
    container_name: slacker_development_db
    env_file:
      - .env
      - .development_env
      - .development_secrets
    environment:
      PGDATABASE: slacker_development
    volumes:
    - development_postgres_data:/data

  zookeeper:
    container_name: slacker_development_zookeeper
    volumes:
    - development_zookeeper_data:/data

  kafka:
    container_name: slacker_development_kafka
    volumes:
    - development_kafka_data:/data

  ksqldb-server:
    container_name: slacker_development_ksqldb-server

  schema:
    container_name: slacker_development_schema
    build:
      context: ./schema
      dockerfile: Dockerfile
    env_file:
      - .env
      - .development_env
      - .development_secrets
    volumes:
    volumes:
    - ./schema:/app
    - ui_assets:/assets
    - ui_bundle:/bundle
    - ui_node_modules:/node_modules

  adminer:
    container_name: slacker_development_adminer

secrets:
  development_secrets:
    file: ./development_secrets.txt

volumes:
  development_postgres_data:
  development_zookeeper_data:
  development_kafka_data:
  auth_node_modules:
  api_node_modules:
  ui_assets:
  ui_bundle:
  ui_node_modules:
