version: '3.3'

services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile.build

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.build

  ui:
    build:
      context: ./ui-service
      dockerfile: Dockerfile.build

  schema:
    build: ./schema
