version: '3.3'

services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3100"
    volumes:
    - ./api-service:/app
    - api_node_modules:/node_modules

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3200"
    volumes:
    - ./auth-service:/app
    - auth_node_modules:/node_modules

  ui:
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    ports:
      - "80"
    volumes:
    - ./ui-service:/app
    - ui_node_modules:/node_modules

  db:
    environment:
      POSTGRES_DB: slacker_development
    ports:
      - "5432"

  zookeeper:
    ports:
      - "2181"

  kafka:
    ports:
      - "9092"

  ksqldb-server:
    ports:
      - "8088"

  schema:
    build:
      context: ./schema
      dockerfile: Dockerfile

  adminer:
    ports:
      - "8080"

volumes:
  auth_node_modules:
  api_node_modules:
  ui_node_modules:
